name: Deploy Polyglot

on:
  push:
    branches: [ main ]
    paths:
      - 'polyglot/**'
      - '.github/workflows/deploy-polyglot.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'polyglot/**'
      - '.github/workflows/deploy-polyglot.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./polyglot
    
    steps:
    - name: 🛒 Grab the code
      uses: actions/checkout@v4
    
    - name: 🟢 Node.js time machine
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './polyglot/package-lock.json'
    
    - name: 📦 Download the internet
      run: npm install
    
    - name: 🧪 Lab experiments
      env:
        OPENAIKEY: fake-key-for-testing
        OPENAI_API_KEY: fake-key-for-testing
      run: npm test
    
    - name: 🎬 Showtime! Deploy!
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_POLYGLOT }}
