name: Kotlin CI/CD

on:
  push:
    paths:
      - 'kotlin/Dockerfile'
      - 'kotlin/.dockerignore'
      - 'kotlin/pom.xml'
      - 'kotlin/src/**'
      - '.github/workflows/kotlin-ci.yml'
  pull_request:
    paths:
      - 'kotlin/Dockerfile'
      - 'kotlin/.dockerignore'
      - 'kotlin/pom.xml'
      - 'kotlin/src/**'
      - '.github/workflows/kotlin-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kotlin
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Run tests
      run: mvn clean test
    
    - name: Build JAR
      run: mvn package -DskipTests
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./kotlin
        file: ./kotlin/Dockerfile
        push: false
        tags: aieng:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker image
      run: |
        docker run -d -p 8080:8080 --name test-container aieng:latest
        sleep 30
        curl -f http://localhost:8080/actuator/health
        docker logs test-container
        docker stop test-container
        docker rm test-container

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and Push image
      run: |
        docker tag aieng:latest ${{ secrets.DOCKERHUB_USER }}/aieng:latest
        docker push ${{ secrets.DOCKERHUB_USER }}/aieng:latest